language: java

jdk:
- openjdk8

env:
  global:
  - secure: B23b9K3vvJrQFtfYEbYglwzHUGZLuEx1FpjBhLWqzDzehb8F4Mhh5EDY9MZ+PlkLggAfqyjwqm8aQP9MWjyUz3wqL1Qu2r1Bo9GoQiQ39DsnkF8oL2bMPwOcj/gDPJwENewdTxVOZ1lRt//5z3qIt3Cj8D1zGf2Eg0jmX1DP7qtGooUwy4e1xYU1COu54QTvgLhhbTzTJB3shwTEptZDo4Kmh69ZgVTjNiFwMSg3tCVc96WZ7J3x0d5s2TfIbwoDCevGzmLmmBFvTTUBoXksyQPlqw8DJ45ctjai+uKKBuRfidH1MMqRLutlSqjPUNMEO3cX/9J4kDODMMEYLoSjq3G/2MaU2sztOIOZCTrsdPOfGLg3llgFveY4cp9esQa3TLa2yUSf4GyO2Yl182y4dK+sM0xYNJcy6/sPZljP8BnGEBFNLgcY/3rKSRurzMCadrxh2p0Qtnn6GHT0zfBCskfvOAD6dT22RYv8eZa/+91C58C5fBzpf7MfXc1oJFoXPnB12TRIJI/m26bjljE+6vCczg5s1uKj5T4WNAi0sRQDv8fiud53lbACSKSwkhXrNTPAtWfL9QaLl1uOplxOlhKLM6utabe1LghjkJiYB05R1RyopPqiEEiPKU5hwSkBG18gqH3fZjdoQzYlJSV4uEvfPo29DA6wFwy3NetoO9Y=
  - secure: AlvkH44Vu902AmAX4pjWzqJVyIKIysZY4+q4zYVjy6Oxcq+4dK3qEO5nzP6u8N94EDYsdgV+OlkKvRKFZ66ZTZMVGinI66RE8oIqQz7g4hqbMSKuYWbxpd+oUW1BcQZdp2q8FZAt7hL6JgY/0ryzDVB+FJbM5+y9JmRcoL07tK1//7K4ILCWJ4JTl+LV8OPchCJ1/UJmndrB9W3orgT1G6Z6tWzguDk1WBxo4IfJz/aX8LI0Qicqk4XOPsjUEX28sqHKe7X9iQZ+XPxWnzTuNafu1mlSGVW5SzgzZ5ioT62eMq99ncuZDVm+MKyCxIVFYON2iLmJO/hgtsLxujx3edGGSB6wVyy0mloCTexT2+bQ+3Cp+1e8qyRD+zt8WMhEtJJTIv6v9SRsGBA/1c6ezhDRZn8D6McyyP9rManZ+KffQ8W9pmgtEzwiDeKGYh6ZvGSMYVZ9G55Wp7epNtsu9b1awjr9qJxiC+wRsEAqDIqnxrojlf9KChZfJBVWG+uMufHiiDtSUK1MDCCCT1s0yGkgdK7Ze0J1Hqf3E8TG40AqMpukrwnPJi3zXqCwZiBvGXpSFR/s5fFdTGxg5knxYHVFV7aaNdnnwswNCXY1uHNNxsLbw8tM8Pzpl8OK+efySKbbTvOitBqdx9Xh69nJgcY/sYF9TSFff77KdiKteuM=
  - secure: NkSloIRlLuDQLG2KaZwDShb/Ixy8B1rYEpVs3RrMfz01dnXYNiIwuxRWqSL56S0sJUTs5HKHE7myDuGNKhRFxRtj6smR824UThE3ac3EbfItt+6D3A+0YpuEdySebyZi5adkZcJWsjwMdSHJv7mz9sM+3sWN9f5H2dRfNL55DB92frX42epmzMKTq1RksQUJM2DnL818IG1CABxJxbY78ZoaHClz0FGcxAmZoKXbswOK49KLNBbJJD/FVNxe1UHDp/AjEHUqx57EJ/xSGFOyL4vG0bjLaHA7lInS0v3dbzlKODLd477oDfPB4oePuyaLycjcNQ3znZjLu7ETpN7TqFQlPPxTXREwo/mB6a4wPicbaS5+rlOv1YF2YqLfWjeAQJRvzgHfNzEkgl1pfCo8mReSl5i9HjJr365Ta38UIqEq2GTOLt4NWsr95RJt+dqf3WW6GRI1k/WGi9n2pyklZ6MBUVf2lVTf0CDRJme8C6Lc8YQ8wYC8OyWt3R8Ya5uxG26ymZSg9tO0GqKhsstBIs49392bww+PPyMRBzRIfcN9fQ+PJFSJlCU1fqiB7e5oOciRs+C8TOCMjxAxcA5wBwKka9fcS7j0wOmobX+ZWzpgHwYPYAn6zp67jJVEWwGS2tma9z0BBkUPLGERKCSNJ8+/yD0BN377VKZji8FyA0g=
  - secure: Su5PJrzWSyFUm9rGyVEfvMEvAiqTMC5tH2qIpBObCTviYUOIy4AzrEocB9J0UtorkffhY2lbCQZeJfTo48YoEMyYRxxu9Z9StnneduZUruSRRFd4eFX4rkjH2ABle74jt+PxIU5Fbb6QoZ+8fe3c9BFdJozjVX71AR10JEKAmIs0qJRJramzB9c+Ld7qrXqRusUgKHL/2vcg3/x6uPn/ZSivAmkwp3z6jAU56nJF38c0YeS3VWWmZr9tneAXSwZYYee1jwv2fttBd69gPvv2VeD3tHRdcMk2CXc65CCQmab6OWsJUuQlSbLuJpDvzCWBikeD5ibnWO6ZKiq6hea412TipwbN8TF3j4Nwnse0u7zwdmTn7U1mUJgiMN3kafW+7bqsRyGT1rqCwlXwhwKxOtywRR4TriDRyanFKQpHUKqatNgrdhkPYYvFndFNlY6IlYQcpmq3ITSDkfRkaqkn4iR37NsZzXMzKtKKcFXlOvHzRMK4djJc83e0OINCK+9aq9nKSM+b/swKZ5uO1b0zSfv4d0rZtO4NcwmR5dPqZUkEyLnee92/XFU2RgKSGZ3lVzFtJEge0tiL6Ntggtw8XYdzXhFTDhnZUCjsVV0KVvjUN67Ob5+3XlgA/3IdgrY4b/JDDkQiOFB9/DC3Dt26TA+MqMthREMsXr5oAWOcRHg=

before_install:
- openssl aes-256-cbc -K $encrypted_79b79e9dd361_key -iv $encrypted_79b79e9dd361_iv
  -in secring.gpg.enc -out secring.gpg -d

install:
- "./gradlew clean"
- "./gradlew assemble"
- "./gradlew allJar"

script:
- "./gradlew check"

before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.name "build@travis-ci.com"

deploy:
- provider: script
  script: ./gradlew publish -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=secring.gpg
  skip_cleanup: true
  on:
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(-.*)?"
    branch: master
    tags: true
- provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: LIA/RjWQcfmFporUHDmkUGY6YyXsGWG5k7v8vZeGm9+g8UiEpkaBXahZhc5AFIAeFOanIExCjLU+A/IwdjZHsdSl78N7gHZVBKpxw5ZB3z7YsQd8tyyAikhKI1G4CveyNJuMOD8gQvTqDO+e/4oILbCrBm8EWL1UrZpPvhKEkwgUuFEcYYA195tgOorzcSx9o/1O9cdJ8G6pwrUSJRjUxG87bgvIGnlDsa2rG8orJmUQixgvuNkHRuy/chfNwbRLOimg/gTsO2B9MbTMchueoppiNfelX6K+b4Kbea2d6YFMk5ac6YX7HruNWa7U4nACJ+k0n7JxSmxOXxdGzb62IBFt1nMimRwlKSqNENe8ugYh7fK1li2UfkPiCd7hTwLYtyAcaEJefUdd3r8rk4ykJvfsUnWMItAZwI2hma/dxuw8s4y/ukFUWo7v72z/Q/rrqk9SJn9mIiZ77BBsebozUcmFS+sx4v0oZclVVA/hkyGN1RZW9tzPx265sAAQ4kp3nGfaSwS8Pkd5vvndaN2X6h1r8ElMgVhB4LkZZo1O/TIlw6H+jQFRRpxZxHuJVU6II2vfxHmU6yWc0byi3edbF3Wwz79hDfczBpaeizdG/9qskqhEcFthjE/O7gyxJAcBAS/zGHIyhxVhjfTQVcPipXbBOPg/wKS6P1Jcur0AAiw=
  file:
  - build/notifier.jar
  - README.md
  on:
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(-.*)?"
    repo: tomtzook/Notifier
    branch: master
    tags: true